coop_tilleuls_sylius_click_n_collect_admin_location:
  resource: |
    alias: coop_tilleuls_click_n_collect.location
    section: admin
    templates: "@CoopTilleulsSyliusClickNCollectPlugin\\Admin\\Crud"
    redirect: update
    grid: coop_tilleuls_click_n_collect_location
    path: /click-n-collect/locations
    permission: true
    vars:
        all:
            subheader: coop_tilleuls_click_n_collect.ui.locations
        index:
            icon: map marker alternate
  type: sylius.resource

coop_tilleuls_sylius_click_n_collect_admin_collections:
  path: /click-n-collect/collections
  controller: coop_tilleuls_click_n_collect.controller.admin.collections
  methods: GET

coop_tilleuls_sylius_click_n_collect_admin_collections_api:
  path: /click-n-collect/collections/{locationCode}
  controller: coop_tilleuls_click_n_collect.controller.admin.collections_api
  methods: GET

coop_tilleuls_sylius_click_n_collect_admin_edit_collection:
  path: /orders/{orderId}/click-n-collect
  controller: coop_tilleuls_click_n_collect.controller.admin.edit_collection
  methods: [GET, PUT]
